"""Added channel_id to videos

Revision ID: 38f0ac778f90
Revises: 05df2ad745a2
Create Date: 2025-02-03 13:06:50.579894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38f0ac778f90'
down_revision: Union[str, None] = '05df2ad745a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('channel_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey')
    )
    op.create_table('videos',
    sa.Column('db_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('host_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('host_service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('db_id', name='videos_pkey')
    )
    # ### end Alembic commands ###
