"""Add description to videos

Revision ID: ac7592c40606
Revises: 38f0ac778f90
Create Date: 2025-02-03 14:23:49.332114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac7592c40606'
down_revision: Union[str, None] = '38f0ac778f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('videos')
    # op.drop_table('users')
    op.add_column('videos', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('videos', 'video_id', new_column_name='host_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'host_id', new_column_name='video_id')
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey')
    )
    op.create_table('videos',
    sa.Column('db_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('host_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('host_service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('db_id', name='videos_pkey')
    )
    # ### end Alembic commands ###
